artifacts_root: artifacts

data_ingestion: 
  root_dirs: artifacts/data_ingestion
  source_url: https://github.com/sumairrasi/data/raw/main/monthly_milk_production.zip
  local_data_file: artifacts/data_ingestion/monthly_milk_production.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dirs: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/monthly_milk_production.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
 root_dirs: artifacts/data_transformation
 data_path: artifacts/data_ingestion/monthly_milk_production.csv

model_trainer:
  root_dirs: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
 root_dirs: artifacts/model_evalution
 train_data_path: artifacts/data_transformation/train.csv
 test_data_path: artifacts/data_transformation/test.csv
 model_path: artifacts/model_trainer/model.joblib
 metric_file_name: artifacts/model_evalution/metrics